Tree.destroy_all


blue_spruce = Tree.create(common_name: "Blue Spruce", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Picea pungens", 
                    bark_color: "gray-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Sharp",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 6700,
                    max_elevation: 11500,
                    min_height: 70,
                    max_height: 115,
                    twig_texture: "Smooth",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "foothills/montane"
                    )         
                    
boxelder = Tree.create(common_name: "Boxelder", 
                    common_fam_name: "Maple", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Acer negundo", 
                    bark_color: "gray-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Opposite",
                    leaf_shape: "Pinnate",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Samara",
                    min_elevation: 4000,
                    max_elevation: 10000,
                    min_height: 5,
                    max_height: 35,
                    twig_texture: "Smooth",
                    flower_shape: "Inconspicuous",
                    flower_color: "Green",
                    habitat: "plains/foothills"
                    )        
                    
bristlecone_pine = Tree.create(common_name: "Bristlecone Pine", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Pinus aristata", 
                    bark_color: "red-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Clusters of 5",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 9200,
                    max_elevation: 11800,
                    min_height: 15,
                    max_height: 30,
                    twig_texture: "Smooth",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "montane/subalpine"
                    )       
                    
chokecherry = Tree.create(common_name: "Chokecherry", 
                    common_fam_name: "Rose", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Prunus virginiana", 
                    bark_color: "red-brown",
                    bark_texture: "Bumpy",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Alternate",
                    leaf_shape: "Oblanceolate",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Fleshy",
                    min_elevation: 5000,
                    max_elevation: 10000,
                    min_height: 10,
                    max_height: 15,
                    twig_texture: "Smooth",
                    flower_shape: "Star or Cross Shaped",
                    flower_color: "White",
                    habitat: "plains/foothills"
                    )     

douglas_fur = Tree.create(common_name: "Douglas Fir", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Pseudotsuga menziesii", 
                    bark_color: "red-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Flat",
                    cone_type: "Papery",
                    fruit: "Cone",
                    min_elevation: 6000,
                    max_elevation: 9500,
                    min_height: 100,
                    max_height: 130,
                    twig_texture: "Rough",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "foothills/montane"
                    )   
                    
engelmann_spruce = Tree.create(common_name: "Engelmann Spruce", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Picea engelmannii", 
                    bark_color: "gray-brown",
                    bark_texture: "Scaled",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Sharp",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 8000,
                    max_elevation: 11000,
                    min_height: 45,
                    max_height: 130,
                    twig_texture: "Hairy",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "montane/subalpine"
                    )     

gambel_oak = Tree.create(common_name: "Gambel Oak", 
                    common_fam_name: "Oak", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Quercus gambelii", 
                    bark_color: "gray-brown",
                    bark_texture: "Scaled",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Alternate",
                    leaf_shape: "Lobed",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Acorn",
                    min_elevation: 4000,
                    max_elevation: 8500,
                    min_height: 10,
                    max_height: 15,
                    twig_texture: "Smooth",
                    flower_shape: "Inconspicuous",
                    flower_color: "Green",
                    habitat: "foothills",
                    )     

limber_pine = Tree.create(common_name: "Limber Pine", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Pinus flexilis", 
                    bark_color: "brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Clusters of 5",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 5000,
                    max_elevation: 12000,
                    min_height: 40,
                    max_height: 50,
                    twig_texture: "Smooth",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "montane/subalpine"
                    )     

lodgepole_pine = Tree.create(common_name: "Lodgepole Pine", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Pinus contorta", 
                    bark_color: "brown",
                    bark_texture: "Scaled",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Clusters of 2-3",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 6000,
                    max_elevation: 11000,
                    min_height: 20,
                    max_height: 80,
                    twig_texture: "Smooth",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "montane/subalpine"
                    )     

narrowleaf_cottonwood = Tree.create(common_name: "Narrowleaf Cottonwood", 
                    common_fam_name: "Willow", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Populus angustifolia", 
                    bark_color: "gray-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Alternate",
                    leaf_shape: "Narrow",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Capsule",
                    min_elevation: 5000,
                    max_elevation: 8000,
                    min_height: 30,
                    max_height: 60,
                    twig_texture: "Smooth",
                    flower_shape: "Inconspicuous",
                    flower_color: "Red",
                    habitat: "foothills/montane"
                    )    
                    
                    
peachleaf_willow = Tree.create(common_name: "Peachleaf Willow", 
                    common_fam_name: "Willow", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Salix amygdaloides", 
                    bark_color: "red-brown",
                    bark_texture: "Smooth",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Alternate",
                    leaf_shape: "Narrow",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Capsule",
                    min_elevation: 3500,
                    max_elevation: 7500,
                    min_height: 10,
                    max_height: 40,
                    twig_texture: "Smooth",
                    flower_shape: "Inconspicuous",
                    flower_color: "Yellow",
                    habitat: "foothills/montane"
                    )         
                    
pinyon_pine = Tree.create(common_name: "Pinyon Pine", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Pinus edulis", 
                    bark_color: "red-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape:"Clusters of 5",
                    cone_type:"Woody",
                    fruit: "Cone",
                    min_elevation: 5200,
                    max_elevation: 9000,
                    min_height: 20,
                    max_height: 50,
                    twig_texture: "Rough",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "foothills/montane"
                    )        
                    
plains_cottonwood = Tree.create(common_name: "Plains Cottonwood", 
                    common_fam_name: "Willow", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Populus deltoides",
                    bark_color: "gray",
                    bark_texture: "Furrowed",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Alternate",
                    leaf_shape: "Deltoid",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Capsule",
                    min_elevation: 3500,
                    max_elevation: 6500,
                    min_height: 36,
                    max_height: 190,
                    twig_texture: "Smooth",
                    flower_shape: "Inconspicuous",
                    flower_color: "Red",
                    habitat: "lower river valleys"
                    )       
                    
ponderosa_pine = Tree.create(common_name: "Ponderosa Pine", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Pinus ponderosa", 
                    bark_color: "red-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Clusters of 2-3",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 6300,
                    max_elevation: 9500,
                    min_height: 40,
                    max_height: 160,
                    twig_texture: "Rough",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "foothills/montane"
                    )     

quaking_aspen = Tree.create(common_name: "Quaking Aspen", 
                    common_fam_name: "Willow", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Populs tremuloides", 
                    bark_color: "gray",
                    bark_texture: "Smooth",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Alternate",
                    leaf_shape: "Orbicular",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Capsule",
                    min_elevation: 6500,
                    max_elevation: 11500,
                    min_height: 35,
                    max_height: 50,
                    twig_texture: "Smooth",
                    flower_shape: "Inconspicuous",
                    flower_color: "White",
                    habitat: "foothills/montane"
                    )   
                    
rocky_mountain_maple = Tree.create(common_name: "Rocky Mountain Maple", 
                    common_fam_name: "Maple", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Acer glabrum", 
                    bark_color: "gray-brown",
                    bark_texture: "Smooth",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Opposite",
                    leaf_shape: "Palmate",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Samara",
                    min_elevation: 3000,
                    max_elevation: 10000,
                    min_height: 20,
                    max_height: 30,
                    twig_texture: "Smooth",
                    flower_shape: "Other",
                    flower_color: "Yellow",
                    habitat: "foothills/montane"
                    )     

rocky_mountain_juniper = Tree.create(common_name: "Rocky Mountan Juniper", 
                    common_fam_name: "Cypress", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Juniperus scopulorum", 
                    bark_color: "gray-brown",
                    bark_texture: "Scaled",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Scaled",
                    cone_type: "Berry",
                    fruit: "Cone",
                    min_elevation: 5000,
                    max_elevation: 9000,
                    min_height: 20,
                    max_height: 50,
                    twig_texture: "Peeling",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "foothills/montane"
                    )     

subalpine_fir = Tree.create(common_name: "Subalpine Fir", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Abies lasiocarpa", 
                    bark_color: "gray-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Flat",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 8000,
                    max_elevation: 12000,
                    min_height: 60,
                    max_height: 100,
                    twig_texture: "Smooth",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "montane/subalpine"
                    )     

thinleaf_alder = Tree.create(common_name: "Thinleaf Alder", 
                    common_fam_name: "Birch", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Alnus tenuifolia", 
                    bark_color: "gray-brown",
                    bark_texture: "Bumpy",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Alternate",
                    leaf_shape: "Orbicular",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Samara",
                    min_elevation: 5000,
                    max_elevation: 10000,
                    min_height: 15,
                    max_height: 40,
                    twig_texture: "Smooth",
                    flower_shape: "Inconspicuous",
                    flower_color: "Red",
                    habitat: "montane"
                    )     

white_fir = Tree.create(common_name: "White Fir", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Abies concolor", 
                    bark_color: "gray",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Flat",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 7900,
                    max_elevation: 10200,
                    min_height: 60,
                    max_height: 125,
                    twig_texture: "Smooth",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "montane"
                    )    
  